// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9nI3yCDn07C589lDLjYt8Q449PFK26XU',
    appId: '1:119849396751:web:2e208ee5f076889125117a',
    messagingSenderId: '119849396751',
    projectId: 'societymanagementproject-c9d7b',
    authDomain: 'societymanagementproject-c9d7b.firebaseapp.com',
    storageBucket: 'societymanagementproject-c9d7b.appspot.com',
    measurementId: 'G-H4WPY9009W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnssme-pqa0Mn-bsilambU1Gu40kheKHE',
    appId: '1:119849396751:android:d0058f41079fb89d25117a',
    messagingSenderId: '119849396751',
    projectId: 'societymanagementproject-c9d7b',
    storageBucket: 'societymanagementproject-c9d7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmacbr60TO1QyUOoy5cFDFRSwSmn9c8vo',
    appId: '1:119849396751:ios:e3777047cdf06f1b25117a',
    messagingSenderId: '119849396751',
    projectId: 'societymanagementproject-c9d7b',
    storageBucket: 'societymanagementproject-c9d7b.appspot.com',
    iosBundleId: 'com.example.societyManagementProjecct',
  );
}
